-- テーブル削除
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS categories;


CREATE TABLE IF NOT EXISTS users (
	user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(20),
	password TEXT
);

CREATE TABLE IF NOT EXISTS tasks (
    task_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    category_id INTEGER,
    title VARCHAR(255),
    closing_date DATE,
    progress VARCHAR(50),
    memo TEXT,
    time INTEGER,
    date DATE
);


CREATE TABLE IF NOT EXISTS categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50)
);
