DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS categories;

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20),
    password TEXT
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20), 
    category_id INTEGER,
    title VARCHAR(255),
    closing_date DATE,
    progress VARCHAR(50),
    memo TEXT,
    time INTEGER,
    date DATE,
    created_at TIMESTAMP,
    started_at TIMESTAMP,
    priority VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50)
);